
name: Node.js CI

on:
  push:
    branches: 
    - master
    - release/*
    - feature/*
    - build/*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present

    - run: cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u ArthurTavaresBezerra --password-stdin
    - run: docker tag IMAGE_ID docker.pkg.github.com/arthurtavaresbezerra/audit_elecion_backend_nodejs/audit_election-backend:latest
    - run: docker push docker.pkg.github.com/arthurtavaresbezerra/audit_elecion_backend_nodejs/audit_election-backend:latest